#!/usr/bin/env bash

#
# Pre-requirements:
# 1) Create remote repository.
#

# Initializes local repo in current directory.
git init .

# Syncs local branch to remote repo"
remote_url=${1}

# Adds a remote named 'origin' to the repo 'remote_urlq'
git remote add origin ${remote_url}

# Verifies remote is set
git remote -v

# Fetches references already created in the remote repo
git fetch

# Sets upstream to master branch located at the remote repo 'origin', defined previously.
git branch -u origin/master
