#!/usr/bin/env bash

#
# Usage: 'git <alias>'. Eg: 'git gb'
#

#*
# Sets 'git alias' depending on the argument, replacing any existing value.
#*
function set() {
    prefix="git config --global --replace-all alias."
    eval "${prefix}${1} \"${2}\""
    echo "****** Validate alias set for '${1}' ***** "
    eval "git config --global --get alias.${1}"
}

# Push force ()
set "gpfl" "push --force-with-lease"

# Pulls remote repo but rebases local commits against remote commits.
set "gpr" "pull --rebase"

# Adds to stage modified or deleted file, changes previous commit message and commits.
set "gca" "commit -a --amend"

# Shows local branches.
set "gb" "branch"

# Shows remote branches.
set "gbr" "branch -r"

# Shows git status.
set "gs" "status"

# Shows a short description of git status with the branch and tracking info
set "gss" "status -bs"

# Shows a colored diff, assuming '=always'
set "gd" "diff --color"

# Shows the abbreviated commit logs in graph format
set "gg" "log --oneline --abbrev-commit --all --graph --decorate --color"

# Shows a short git log.
set "glog" "log --oneline"

set "glogd" "log --name-only --oneline"

set "glastci" "diff-tree --no-commit-id --name-only -r HEAD"
