#!/usr/bin/env bash
#
# Sets a pub/priv key per host arg, so that multiple deploy-keys can be used for the same host in GitHub.
# @params:
#   1=repository_name
#
function set-deploykey-per-host () {
    repo_name=${1}

    # Validate mandatory args
    if [[ -z ${repo_name} ]]; then
        echo "No repository_name was found. Skipping..."
        exit 1
    fi

    repo_name=${1}
    description=${2}

    # Generate key pair for the given args.
    ssh-keygen -t rsa -f ~/.ssh/${repo_name} -C "${description: ${repo_name}}"

    echo "********** Copy+paste output to GitHub deploy key ********** "
    cat ~/.ssh/${repo_name}.pub


    echo "
    ###### GitHub repository reference

    Host github-${repo_name}
    HostName github.com
    User git
    IdentityFile ~/.ssh/${repo_name}
    " >> ~/.ssh/config
}
