#!/usr/bin/env bash

# 'includes' / loads file contents.
function include() {
    local path=$1
    for file in  $(find "$path" -type f -print)
    do
        source ${file}
    done
}

#Loads exports
echo "Exporting everyday-scripts lib/*"
include ${everyday_scripts_path:-.}/lib/exports

#Loads commands.
echo "Initializing everyday-scripts lib/*"
include ${everyday_scripts_path:-.}/lib/init




