#!/usr/bin/env bash

# Checks out a remote project to the local repo and sets upstream,q
if [[ -z "$1" ]]; then
    echo "No argument was found."
    exit 1
else
    remote_branch_name=${1}
    echo "Checking out branch: $remote_branch_name"
    git checkout --track origin ${remote_branch_name}
fi



