#!/usr/bin/env bash


alias ls='ls -lart'

alias cp='cp -vi'

alias  df='df -h'
alias  du='du -h'

alias  mv='mv -i'
alias  rm='rm -i'

# Lazy ancestor directory ziggurat of doom
alias        ..='cd ..'
alias       ...='cd ../..'
alias      ....='cd ../../..'
alias     .....='cd ../../../..'
alias    ......='cd ../../../../..'
alias   .......='cd ../../../../../..'
alias  ........='cd ../../../../../../..'
alias .........='cd ../../../../../../../..'

