#!/usr/bin/env bash

#
# Usage: 'git <alias>'. Eg: 'git gb'
#

#*
# Sets 'git alias' depending on the argument, replacing any existing value.
#*
function setAlias() {
    prefix="git config --global --replace-all alias."
    eval "${prefix}${1} \"${2}\""
    echo "****** Validate alias set for '${1}' ***** "
    eval "git config --global --get alias.${1}"
}

# Push force ()
setAlias "gpfl" "push --force-with-lease"

# Pulls remote repo but rebases local commits against remote commits.
setAlias "gpr" "pull --rebase"

# Adds to stage modified or deleted file, changes previous commit message and commits.
setAlias "gca" "commit -a --amend"

# Shows local branches.
setAlias "gb" "branch"

# Shows remote branches.
setAlias "gbr" "branch -r"

# Shows git status.
setAlias "gs" "status"

# Shows a short description of git status with the branch and tracking info
setAlias "gss" "status -bs"

# Shows a colored diff, assuming '=always'
setAlias "gd" "diff --color"

# Shows the abbreviated commit logs in graph format
setAlias "gg" "log --oneline --abbrev-commit --all --graph --decorate --color"

# Shows a short git log.
setAlias "glog" "log --oneline"

setAlias "glogd" "log --name-only --oneline"

setAlias "glastci" "diff-tree --no-commit-id --name-only -r HEAD"



###################################################################
## git colors
###################################################################

echo "Git colors..."
# Enable tab completion
source ~/.git-completion.bash

# colors!
green="\[\033[0;32m\]"
blue="\[\033[0;34m\]"
purple="\[\033[0;35m\]"
reset="\[\033[0m\]"

# Change command prompt
source ~/.git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=1

# '\u' adds the name of the current user to the prompt
# '\$(__git_ps1)' adds git-related stuff
# '\W' adds the name of the current directory
export PS1="$purple\u$green\$(__git_ps1)$blue \W $ $reset"
